#!/usr/bin/env bash

if ! type brew >/dev/null; then
  echo "please install homebrew"
  echo "  https://brew.sh/"
  exit 1
fi

if ! type ansible-playbook >/dev/null; then
  echo "please install ansible"
  echo "  brew install ansible"
  exit 1
fi

ansible-playbook bootstrap.yml