#!/usr/bin/env bash

backup_path="$HOME/.kube/config-backup"

echo "backing up existing config to $backup_path"
cp "$HOME/.kube/config" "$backup_path"
echo "done"

echo
echo "looking for config files"
KUBECONFIG="$(find "$HOME/.kube" -type f -iname '*.yaml' | tr '\n' ':')"
echo "found $KUBECONFIG"

echo
echo "merging config files"
kubectl config view --flatten >"$HOME/.kube/config"

echo
echo "please check that the merged config is correct, e.g. with kubectl config get-clusters:"
kubectl config get-clusters

echo
read -rp "remove backup at $backup_path [y/N]? " remove_backup
case $remove_backup in
[yY][eE][sS] | [yY])
  rm "$backup_path"
  echo "backup removed"
  ;;
*)
  echo "backup kept"
  ;;
esac
